version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/install.postgres.sql:/tmp/app/install.postgres.sql
      - ./backend/db/data.postgres.sql:/tmp/app/data.postgres.sql
      - ./backend/db/docker.init.sh:/docker-entrypoint-initdb.d/docker.init.sh

  backend:
    depends_on:
      - db
    container_name: backend
    image: training-backend
    environment:
      - DB_TYPE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app
    build:
      context: backend
    ports:
      - "5000:80"

  frontend:
    container_name: front
    image: training-frontend
    build:
      context: frontend
      args:
        API_URL: http://localhost:5000
    ports:
      - "5001:80"